### ISSUE TITLE
read: -p: no coprocess

### ISSUE THREAD

**Issue by dzintars** [dzintars/infra#25]
The issue was that **Vim** is not installed on the system and there is no alias created as well.
To add the alias to the **Nvim**, just use this rule.
```yaml
- name: add vim alias
  lineinfile:
    path: $HOME/.zshrc
    line: "alias vim='nvim'"
    owner: "{{ become_user }}"
    regexp: "^alias vim='nvim'$"
    state: present
    insertafter: '^# Aliases'
    # create: True
```
